language: java

jdk:
  - oraclejdk7

script:
  - ./travis.sh

install: true

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "KzUYvJtfK8ejhhDTTOzDu/qUzcF+kxx931O+WgMfWYW6BMBCAM9bOcLF14hBhOYlBuvmwY2tQCqhLMdJfMr2VHV47uvnQ5gCg1h86LETq1CMJS17++b3avSsg021RHTXD1ajsJvFctFdhRzOM5cTkGqK4k8dg6dCFgz71nxqaDKUjr4HAkGprZxe3q+CnU/1f44SOfFjgeNT17z67IscErx1MuCDg5Nf0LbWaDGFcrlHxTbHxPdVd1+GLnshpIZj07mvzIZlo4Rl8hih998XE/gMh3a9fl+Cico1I9odFnt4W1U2GJIagrlHGwqqkhXMnzd3cmFJVYH84JwtvD1u4SUkpZjSxDatI9h7L3BpKHpxKdileP5uWz3LJIz2ZaDXU/tFz9uWFqFGem/bIoa6jZUbz/o1Cs0tmYIHakuJ5cfTCLB0/agsGEsbJnVaZcotj3+BErkXcynfr3fuQ1/GRv3PwRlPWeVPaYoB5Z8YKtzI6wEdJypSu+sukVVyi5e3cg3D7vgNIjUdYTKJAWrDdA99HmUTXlEiGuXIgGz08LerSF+uWhuK1xQVBGgIj+hIJiAmQAdGQIojnI1X2waKFjKnHS8Xz0Jor9WG7h4aAhWBnHQW5zh8Qe72CirnOIuEDJgOZrhu06MBknHZxVOU9LWjYh+/IsJvSEp7xbkSYMw="
